spring.application.name=rag-with-springboot-vectordb
server.port=8099

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5433/rag_demo
spring.datasource.username=vectoruser
spring.datasource.password=vectorpassword
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create

# Spring AI OpenAI Configuration
spring.ai.openai.base-url=http://127.0.0.1:1234/v1
spring.ai.openai.api-key=""
#spring.ai.openai.embedding.options.model=text-embedding-nomic-embed-text-v2-moe
spring.ai.openai.embedding.options.model=text-embedding-nomic-embed-text-v1.5
spring.ai.openai.embedding.options.dimensions=768

spring.ai.openai.chat.base-url=https://openrouter.ai/api/v1
spring.ai.openai.chat.api-key=${OPENROUTER_API_KEY}
spring.ai.openai.chat.options.model=google/gemini-2.5-flash
spring.ai.openai.chat.options.max-tokens=4096

# Spring AI PgVector Configuration
spring.ai.vectorstore.pgvector.index-type=HNSW
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE
spring.ai.vectorstore.pgvector.dimensions=768
spring.ai.vectorstore.pgvector.max-document-batch-size=10000
spring.ai.vectorstore.pgvector.schema-validation=true
spring.ai.vectorstore.pgvector.table-name=vector_store